import "./globals.css";
import Header from "./components/Header";

export const metadata = {
  title: "Space Tourism",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-black text-white overflow-hidden'>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
